env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
  dot-location:
    - error
    - property
  function-paren-newline:
    - error
    - consistent
  comma-spacing:
    - error
    - after: true
  comma-style:
    - error
    - last
  func-call-spacing:
    - error
    - never
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  arrow-spacing:
    - error
  function-call-argument-newline:
    - error
    - consistent
  key-spacing:
    - error
  keyword-spacing:
    - error
  max-len:
    - error
    - code: 120
  no-multi-spaces: [error]
  no-trailing-spaces: [error]
  no-whitespace-before-property: "error"
  space-before-blocks: "error"
  space-in-parens: ["error", "never"]
  rest-spread-spacing: ["error"]
  curly: "error"
  array-bracket-spacing: ["error", "never"]
  array-bracket-newline: ["error", "consistent"]
  array-element-newline: ["error", "consistent"]
  computed-property-spacing: ["error", "never"]
  object-curly-spacing: ["error", "always"]
  block-spacing: error
  sort-imports:
    - error
    - ignoreCase: true
    # - ignoreDeclarationSort: false
    # - ignoreMemberSort: false
    # - allowSeparatedGroups: false